### ISSUE TITLE
pip install DisplayCAL - dist/copyright : doesn't exist - Ubuntu 22.04 python 3.10 

### ISSUE THREAD

**Issue by bjornjm** [eoyilmaz/displaycal-py3#251]
Tried to install via pip install DisplayCAL
on my Ubuntu 22:04 machine

```shell
(5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64)
```

with 

```shell
$ python3 --version
Python 3.10.6
```

I get when I run pip install DisplayCAL

```shell
  Building wheel for DisplayCAL (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for DisplayCAL (pyproject.toml) did not run successfully.
  │ exit code: 1
```

and further down:

```shell
error: can't copy '/tmp/pip-install-sjfisrkw/displaycal_8b3724605b2f48fb90df1680d36d6109/DisplayCAL/../dist/copyright': doesn't exist or not a regular file
```

Tried the original build instructions also but got stuck. I am quite OK on Unix/Linux but somewhat new to python.

/Björn

**Comment by fafoune007** [comment]
Hello,

I have exactly the same problem (with same Ubuntu and Python versions)

Steph

**Comment by p5k369** [comment]
Hey @bjornjm and @fafoune007,
please share your console log, input and output. Are you in a virtual machine? Doesn't look like that, we highly recommend that.
Also to help you, more information is needed besides being stuck. An alternative is to try the very detailed tour here: https://github.com/eoyilmaz/displaycal-py3/issues/246#issuecomment-1510426915

**Comment by Wedge009** [comment]
Have just run into the same issue, after manually installing attrdict3 (#235):

```
Building wheels for collected packages: DisplayCAL, wxPython
  Building wheel for DisplayCAL (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for DisplayCAL (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [354 lines of output]
      ['bdist_wheel', '--dist-dir', '/tmp/pip-wheel-3d7cth2w/tmpihyuohwg']
      *** /usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py bdist_wheel --dist-dir /tmp/pip-wheel-3d7cth2w/tmpihyuohwg
      using distutils
      desktopfile: /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/DisplayCAL/../misc/displaycal.desktop
      desktopfile: /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/DisplayCAL/../misc/displaycal-3dlut-maker.desktop
      desktopfile: /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/DisplayCAL/../misc/displaycal-apply-profiles.desktop
      desktopfile: /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/DisplayCAL/../misc/displaycal-curve-viewer.desktop
      desktopfile: /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/DisplayCAL/../misc/displaycal-profile-info.desktop
      desktopfile: /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/DisplayCAL/../misc/displaycal-scripting-client.desktop
      desktopfile: /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/DisplayCAL/../misc/displaycal-synthprofile.desktop
      desktopfile: /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/DisplayCAL/../misc/displaycal-testchart-editor.desktop
      desktopfile: /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/DisplayCAL/../misc/displaycal-vrml-to-x3d-converter.desktop
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/audio.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/__main__.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/taskbar.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/imfile.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/__init__.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/cubeiterator.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/colormath.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/log.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wxScriptingClient.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/chromecast_patterngenerator.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/webwin.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wxCCXXPlot.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wxfixes.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/util_x.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/edid.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/__version__.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/postinstall.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/argyll_RGB2XYZ.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/profile_loader.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/colord.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/systrayicon.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wxTestchartEditor.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wxaddons.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/config.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/util_mac.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/util_decimal.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wxLUT3DFrame.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/meta.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/util_xml.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/RealDisplaySizeMM.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/worker_base.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/multiprocess.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/jspacker.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/xh_filebrowsebutton.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wexpect.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/encoding.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/embeddedimage.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/jsondict.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/floatspin.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wxwindows.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/localization.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/network.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wxLUTViewer.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/argyll_cgats.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/setup.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/debughelpers.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/win_knownpaths.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wxversion.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/util_io.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/x3dom.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/pyi_md5pickuphelper.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/worker.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/taskscheduler.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/encodedstdio.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/util_win.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/util_list.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/ccmx.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/util_http.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wxVisualWhitepointEditor.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/util_dict.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wxUntetheredFrame.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/win_handles.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/util_dbus.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/madvr.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/win_structs.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/xrandr.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/display_cal.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/util_str.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wxSynthICCFrame.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wxDisplayUniformityFrame.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wxReportFrame.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wxenhancedplot.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/gtypes.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/xh_bitmapctrls.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/demjson_compat.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/main.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/xh_floatspin.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/defaultpaths.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/report.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/options.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/xh_hstretchstatbmp.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/CGATS.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wxDisplayAdjustmentFrame.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/patterngenerators.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/xh_fancytext.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/util_os.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/argyll_names.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wxMeasureFrame.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/argyll_instruments.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/lazydict.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/ICCProfile.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wxVRML2X3D.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/wxProfileInfo.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      copying DisplayCAL/safe_print.py -> build/lib.linux-x86_64-3.10/DisplayCAL
      creating build/lib.linux-x86_64-3.10/DisplayCAL/lib
      copying DisplayCAL/lib/__init__.py -> build/lib.linux-x86_64-3.10/DisplayCAL/lib
      creating build/lib.linux-x86_64-3.10/DisplayCAL/lib/agw
      copying DisplayCAL/lib/agw/gradientbutton.py -> build/lib.linux-x86_64-3.10/DisplayCAL/lib/agw
      copying DisplayCAL/lib/agw/__init__.py -> build/lib.linux-x86_64-3.10/DisplayCAL/lib/agw
      copying DisplayCAL/lib/agw/fourwaysplitter.py -> build/lib.linux-x86_64-3.10/DisplayCAL/lib/agw
      copying DisplayCAL/lib/agw/fmresources.py -> build/lib.linux-x86_64-3.10/DisplayCAL/lib/agw
      copying DisplayCAL/lib/agw/labelbook.py -> build/lib.linux-x86_64-3.10/DisplayCAL/lib/agw
      copying DisplayCAL/lib/agw/artmanager.py -> build/lib.linux-x86_64-3.10/DisplayCAL/lib/agw
      copying DisplayCAL/lib/agw/pygauge.py -> build/lib.linux-x86_64-3.10/DisplayCAL/lib/agw
      running build_ext
      creating build/temp.linux-x86_64-3.10
      creating build/temp.linux-x86_64-3.10/DisplayCAL
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DUNIX -I/usr/include/python3.10 -c DisplayCAL/RealDisplaySizeMM.c -o build/temp.linux-x86_64-3.10/DisplayCAL/RealDisplaySizeMM.o
      DisplayCAL/RealDisplaySizeMM.c: In function ‘get_displays’:
      DisplayCAL/RealDisplaySizeMM.c:871:61: warning: pointer targets in passing argument 11 of ‘XRRGetOutputProperty’ differ in signedness [-Wpointer-sign]
        871 |                                     &ret_type, &ret_format, &ret_len, &ret_togo, &atomv) == Success
            |                                                             ^~~~~~~~
            |                                                             |
            |                                                             long int *
      In file included from DisplayCAL/RealDisplaySizeMM.c:33:
      /usr/include/X11/extensions/Xrandr.h:340:38: note: expected ‘long unsigned int *’ but argument is of type ‘long int *’
        340 |                       unsigned long *nitems, unsigned long *bytes_after,
            |                       ~~~~~~~~~~~~~~~^~~~~~
      DisplayCAL/RealDisplaySizeMM.c:871:71: warning: passing argument 12 of ‘XRRGetOutputProperty’ from incompatible pointer type [-Wincompatible-pointer-types]
        871 |                                     &ret_type, &ret_format, &ret_len, &ret_togo, &atomv) == Success
            |                                                                       ^~~~~~~~~
            |                                                                       |
            |                                                                       long unsigned int **
      In file included from DisplayCAL/RealDisplaySizeMM.c:33:
      /usr/include/X11/extensions/Xrandr.h:340:61: note: expected ‘long unsigned int *’ but argument is of type ‘long unsigned int **’
        340 |                       unsigned long *nitems, unsigned long *bytes_after,
            |                                              ~~~~~~~~~~~~~~~^~~~~~~~~~~
      DisplayCAL/RealDisplaySizeMM.c:1036:53: warning: pointer targets in passing argument 10 of ‘XGetWindowProperty’ differ in signedness [-Wpointer-sign]
       1036 |                             &ret_type, &ret_format, &ret_len, &ret_togo, &atomv) == Success
            |                                                     ^~~~~~~~
            |                                                     |
            |                                                     long int *
      In file included from DisplayCAL/RealDisplaySizeMM.c:27:
      /usr/include/X11/Xlib.h:2696:5: note: expected ‘long unsigned int *’ but argument is of type ‘long int *’
       2696 |     unsigned long*      /* nitems_return */,
            |     ^~~~~~~~~~~~~~
      DisplayCAL/RealDisplaySizeMM.c:1036:63: warning: pointer targets in passing argument 11 of ‘XGetWindowProperty’ differ in signedness [-Wpointer-sign]
       1036 |                             &ret_type, &ret_format, &ret_len, &ret_togo, &atomv) == Success
            |                                                               ^~~~~~~~~
            |                                                               |
            |                                                               long int *
      In file included from DisplayCAL/RealDisplaySizeMM.c:27:
      /usr/include/X11/Xlib.h:2697:5: note: expected ‘long unsigned int *’ but argument is of type ‘long int *’
       2697 |     unsigned long*      /* bytes_after_return */,
            |     ^~~~~~~~~~~~~~
      DisplayCAL/RealDisplaySizeMM.c: In function ‘enumerate_displays’:
      DisplayCAL/RealDisplaySizeMM.c:1364:56: warning: pointer targets in passing argument 1 of ‘PyBytes_FromStringAndSize’ differ in signedness [-Wpointer-sign]
       1364 |               (value = PyString_FromStringAndSize(dp[i]->edid, dp[i]->edid_len)) != NULL) {
            |                                                   ~~~~~^~~~~~
            |                                                        |
            |                                                        unsigned char *
      In file included from /usr/include/python3.10/Python.h:82,
                       from DisplayCAL/RealDisplaySizeMM.c:1:
      /usr/include/python3.10/bytesobject.h:34:50: note: expected ‘const char *’ but argument is of type ‘unsigned char *’
         34 | PyAPI_FUNC(PyObject *) PyBytes_FromStringAndSize(const char *, Py_ssize_t);
            |                                                  ^~~~~~~~~~~~
      creating build/lib.linux-x86_64-3.10/DisplayCAL/lib64
      creating build/lib.linux-x86_64-3.10/DisplayCAL/lib64/python310
      x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-3.10/DisplayCAL/RealDisplaySizeMM.o -L/usr/lib/x86_64-linux-gnu -lX11 -lXinerama -lXrandr -lXxf86vm -o build/lib.linux-x86_64-3.10/DisplayCAL/lib64/python310/RealDisplaySizeMM.cpython-310-x86_64-linux-gnu.so
      running build_scripts
      creating build/scripts-3.10
      running install
      running install_lib
      creating build/bdist.linux-x86_64
      creating build/bdist.linux-x86_64/wheel
      creating build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/audio.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/__main__.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/taskbar.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/imfile.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/__init__.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/cubeiterator.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/colormath.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/log.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wxScriptingClient.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/chromecast_patterngenerator.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/webwin.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wxCCXXPlot.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wxfixes.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/util_x.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/edid.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/__version__.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/postinstall.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/argyll_RGB2XYZ.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/profile_loader.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/colord.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/systrayicon.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wxTestchartEditor.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wxaddons.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/config.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/util_mac.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/util_decimal.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wxLUT3DFrame.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/meta.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/util_xml.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/RealDisplaySizeMM.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/worker_base.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/multiprocess.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/jspacker.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      creating build/bdist.linux-x86_64/wheel/DisplayCAL/lib
      copying build/lib.linux-x86_64-3.10/DisplayCAL/lib/__init__.py -> build/bdist.linux-x86_64/wheel/DisplayCAL/lib
      creating build/bdist.linux-x86_64/wheel/DisplayCAL/lib/agw
      copying build/lib.linux-x86_64-3.10/DisplayCAL/lib/agw/gradientbutton.py -> build/bdist.linux-x86_64/wheel/DisplayCAL/lib/agw
      copying build/lib.linux-x86_64-3.10/DisplayCAL/lib/agw/__init__.py -> build/bdist.linux-x86_64/wheel/DisplayCAL/lib/agw
      copying build/lib.linux-x86_64-3.10/DisplayCAL/lib/agw/fourwaysplitter.py -> build/bdist.linux-x86_64/wheel/DisplayCAL/lib/agw
      copying build/lib.linux-x86_64-3.10/DisplayCAL/lib/agw/fmresources.py -> build/bdist.linux-x86_64/wheel/DisplayCAL/lib/agw
      copying build/lib.linux-x86_64-3.10/DisplayCAL/lib/agw/labelbook.py -> build/bdist.linux-x86_64/wheel/DisplayCAL/lib/agw
      copying build/lib.linux-x86_64-3.10/DisplayCAL/lib/agw/artmanager.py -> build/bdist.linux-x86_64/wheel/DisplayCAL/lib/agw
      copying build/lib.linux-x86_64-3.10/DisplayCAL/lib/agw/pygauge.py -> build/bdist.linux-x86_64/wheel/DisplayCAL/lib/agw
      copying build/lib.linux-x86_64-3.10/DisplayCAL/xh_filebrowsebutton.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wexpect.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/encoding.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/embeddedimage.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/jsondict.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/floatspin.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wxwindows.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/localization.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/network.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wxLUTViewer.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/argyll_cgats.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/setup.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/debughelpers.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/win_knownpaths.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wxversion.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/util_io.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/x3dom.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/pyi_md5pickuphelper.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/worker.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/taskscheduler.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/encodedstdio.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/util_win.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/util_list.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/ccmx.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/util_http.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wxVisualWhitepointEditor.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/util_dict.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wxUntetheredFrame.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/win_handles.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/util_dbus.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/madvr.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/win_structs.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      creating build/bdist.linux-x86_64/wheel/DisplayCAL/lib64
      creating build/bdist.linux-x86_64/wheel/DisplayCAL/lib64/python310
      copying build/lib.linux-x86_64-3.10/DisplayCAL/lib64/python310/RealDisplaySizeMM.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/DisplayCAL/lib64/python310
      copying build/lib.linux-x86_64-3.10/DisplayCAL/xrandr.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/display_cal.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/util_str.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wxSynthICCFrame.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wxDisplayUniformityFrame.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wxReportFrame.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wxenhancedplot.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/gtypes.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/xh_bitmapctrls.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/demjson_compat.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/main.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/xh_floatspin.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/defaultpaths.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/report.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/options.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/xh_hstretchstatbmp.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/CGATS.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wxDisplayAdjustmentFrame.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/patterngenerators.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/xh_fancytext.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/util_os.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/argyll_names.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wxMeasureFrame.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/argyll_instruments.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/lazydict.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/ICCProfile.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wxVRML2X3D.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/wxProfileInfo.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      copying build/lib.linux-x86_64-3.10/DisplayCAL/safe_print.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      running install_data
      creating build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data
      creating build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data
      creating build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share
      creating build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc
      creating build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/CHANGES.html -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/README.html -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/README-fr.html -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal
      creating build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME-adjust.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME-calibration-settings.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME-profile-information-thumb.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-Win10-thumb.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME-view-curves-thumb.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-Win10.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME-adjust-thumb.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME-verification-settings.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME-verification-settings-thumb.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME-edit-testchart.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-KDE5-thumb.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-KDE5.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME-view-curves.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME-edit-testchart-thumb.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME-adjust-1024x576.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME-profile-information.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME-1024x576.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME-thumb.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-Mac-thumb.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-Mac.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME-calibration-settings-thumb.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME-3DLUT-settings.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME-profiling-settings-thumb.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME-profiling-settings.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/screenshots/DisplayCAL-screenshot-GNOME-3DLUT-settings-thumb.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/screenshots
      creating build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/DisplayCAL-main_window-reflection-Mac.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/DisplayCAL-adjust-reflection-Mac.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/DisplayCAL-main_window-shadow.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/bg.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/DisplayCAL-adjust-reflection-GNOME.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/DisplayCAL-main_window-shadow-GNOME.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/DisplayCAL-adjust-reflection.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/DisplayCAL-main_window-shadow-Mac.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/list-dot.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/DisplayCAL-main_window-reflection.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/DisplayCAL-main_window-reflection-GNOME.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/icon-reflection.png -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/readme.css -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/prism.css -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/jquery.scrollTo.js -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/jquery.js -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/readme.js -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/jquery.localscroll.js -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/prism.js -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/refresh.svg -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme
      creating build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme/icons
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/icons/favicon.ico -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme/icons
      creating build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme/slimbox2
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/slimbox2/slimbox2.css -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme/slimbox2
      copying /tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/theme/slimbox2/slimbox2.js -> build/bdist.linux-x86_64/wheel/DisplayCAL-3.9.10.data/data/share/doc/displaycal/theme/slimbox2
      error: can't copy '/tmp/pip-install-6kjijfdm/displaycal_9fd072b3faa74d00b472b7858bc1a9f7/DisplayCAL/../dist/copyright': doesn't exist or not a regular file
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for DisplayCAL
  Building wheel for wxPython (setup.py) ... /^[[done
  Created wheel for wxPython: filename=wxPython-4.2.0-cp310-cp310-linux_x86_64.whl size=146331256 sha256=0c8bb7cdfe54c1c047b9f55a9898dab58d242653ed70c73ee137559b539290ec
  Stored in directory: /home/[redacted]/.cache/pip/wheels/d5/e6/93/0b409fe8fac74ec4bf88afb1355a450e7eaeaa93bce112c554
Successfully built wxPython
Failed to build DisplayCAL
ERROR: Could not build wheels for DisplayCAL, which is required to install pyproject.toml-based projects
```

**Comment by JacekRuzyczka** [comment]
The build process can't copy the copyright file 'cause it's either missing in the DisplayCAL package distributed via PyPi / pip, or it hasn't been generated earlier in the build process. I think you should talk to the maintainer of `displaycal-python3`.

**Comment by Wedge009** [comment]
> I think you should talk to the maintainer of `displaycal-python3`.

Sorry for misunderstanding, but I thought that was this project. Who would the maintainer be?

**Comment by JacekRuzyczka** [comment]
This IS the DisplayCAL project, but I haven't seen the maintainer (the owner of this project) for more than one week here. :/

**Comment by p5k369** [comment]
@Wedge009 just tested the pip package, installed without any issues.
If you need assistance post your complete input. Do **not** try to pip install into your system, use a virtual environment instead.

**Comment by Wedge009** [comment]
Hmm, odd. I tried a virtual environment as well - same error message against `dist/copyright`.

Which distribution were you successful in installing?

'complete input':
```
python3 -m venv venv
source venv/bin/activate
pip install displaycal
```

**Comment by bjornjm** [comment]
Hi,
I also get the same error using the virtual environment:

python3 -m venv venv
source venv/bin/activate
pip install attrdict3
pip install displaycal

getting very similar error as before:

      *** /home/medin/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py bdist_wheel --dist-dir /tmp/pip-wheel-p_yzpo14/.tmp-rtxvu9kw
      using distutils
      desktopfile: /tmp/pip-install-d3zeuc5g/displaycal_f95330ca7c184f708380bea4723fb30c/DisplayCAL/../misc/displaycal.desktop
      desktopfile: /tmp/pip-install-d3zeuc5g/displaycal_f95330ca7c184f708380bea4723fb30c/DisplayCAL/../misc/displaycal-3dlut-maker.desktop
      desktopfile: /tmp/pip-install-d3zeuc5g/displaycal_f95330ca7c184f708380bea4723fb30c/DisplayCAL/../misc/displaycal-apply-profiles.desktop
      desktopfile: /tmp/pip-install-d3zeuc5g/displaycal_f95330ca7c184f708380bea4723fb30c/DisplayCAL/../misc/displaycal-curve-viewer.desktop
      desktopfile: /tmp/pip-install-d3zeuc5g/displaycal_f95330ca7c184f708380bea4723fb30c/DisplayCAL/../misc/displaycal-profile-info.desktop
      desktopfile: /tmp/pip-install-d3zeuc5g/displaycal_f95330ca7c184f708380bea4723fb30c/DisplayCAL/../misc/displaycal-scripting-client.desktop
      desktopfile: /tmp/pip-install-d3zeuc5g/displaycal_f95330ca7c184f708380bea4723fb30c/DisplayCAL/../misc/displaycal-synthprofile.desktop
      desktopfile: /tmp/pip-install-d3zeuc5g/displaycal_f95330ca7c184f708380bea4723fb30c/DisplayCAL/../misc/displaycal-testchart-editor.desktop
      desktopfile: /tmp/pip-install-d3zeuc5g/displaycal_f95330ca7c184f708380bea4723fb30c/DisplayCAL/../misc/displaycal-vrml-to-x3d-converter.desktop
      error: can't copy '/tmp/pip-install-d3zeuc5g/displaycal_f95330ca7c184f708380bea4723fb30c/DisplayCAL/../dist/copyright': doesn't exist or not a regular file
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for displaycal

**Comment by p5k369** [comment]
Now that's interesting. In fact ubuntu is a distro that handles python a little bit different than others. In regards of what gets installed if we talk about a python installation.
I will change the title to match the issue more precise. Also I will set up a vm with ubuntu but that might take some time.

@Wedge009 I'm on gentoo

**Comment by 3ll3d00d** [comment]
same problem on debian using a pyenv installed version of python

**Comment by p5k369** [comment]
I can now confirm that this is a debian/ubuntu specific problem. There seems to be a general problem with the pip package but with distributions like fedora or gentoo it is at least possible to install displaycal via pip locally. 
That is not the case with debian/ubuntu, also both complain about a file missing, that no other distribution does.
What does work is, if you follow the instructions on the main page.
Create a venv, clone the repository and install via 
```
pip install -r requirements.txt
python -m build
pip install dist/DisplayCAL-3.9.*.whl
```

**Comment by eoyilmaz** [comment]
Closing this because of inactivity... Open it back if required.

**Comment by CrystalSplitter** [comment]
Hi, came across this issue on Kubuntu 24.04 for the pip package and I can confirm, this is still a problem. I would request this being reopened.

Reproduction in my case:

```
sudo apt-get install build-essential dbus libglib2.0-dev pkg-config libgtk-3-dev libxxf86vm-dev
pipx install DisplayCAL
```

**Comment by guillaumedavidphd** [comment]
Same issue as @CrystalSplitter with a comparable system.

**Comment by eoyilmaz** [comment]
Confirming this is occuring in Ubuntu 24.10 too...

**Comment by eoyilmaz** [comment]
This should now be solved with #348 , can you please try to use the steps to build DisplayCAL from source and try running it as explained [here](https://github.com/eoyilmaz/displaycal-py3/?tab=readme-ov-file#build-from-source-makefile-workflow-linux--macos).

**Comment by guillaumedavidphd** [comment]
This is still a problem. Building from source works but `pip install`ing fails with the above `error: can't copy '{...}/DisplayCAL/../dist/copyright': doesn't exist or not a regular file` error still.

**Comment by eoyilmaz** [comment]
This is so confusing, I think the problem occurs because I'm uploading the source package from my Macbook. When I generate the source package (tar.gz) in the ubuntu virtual machine it installs without any problem.

**Comment by eoyilmaz** [comment]
Here, try this one, it is generated under Ubuntu: 
[displaycal-3.9.14.tar.gz](https://github.com/user-attachments/files/17413623/displaycal-3.9.14.tar.gz)

**Comment by guillaumedavidphd** [comment]
I can confirm that `python -m pip install displaycal-3.9.14.tar.gz` works with the archive above.

**Comment by eoyilmaz** [comment]
Then maybe it is better my to create and upload the source tarball from Ubuntu 🤔 I wonder if we are going to have issues in other OSes then...

**Comment by eoyilmaz** [comment]
@guillaumedavidphd can you try installing this tarball: [displaycal-3.9.14.tar.gz](https://github.com/user-attachments/files/17431803/displaycal-3.9.14.tar.gz)

which I generated from MacOS again, let's see if this is going to work.

**Comment by guillaumedavidphd** [comment]
The tarball above worked for me.

**Comment by eoyilmaz** [comment]
cool... it means that it is going to work when installed through PyPI too...

I'm going to follow my usual workflow or creating a PR and closing this, but keep an eye and re-open or message here again if 3.9.15 (hopefully released soon) is not working for you.

**Comment by CrystalSplitter** [comment]
Sorry for the delay in response. I wanted to confirm to you that the above tarballs worked!

```fish
┌ ~/D/python_venv
╰ source env/bin/activate.fish
(env) ┌ ~/D/python_venv
╰ ls
displaycal-3.9.14.tar.gz  env/
(env) ┌ ~/D/python_venv
╰ pip install displaycal-3.9.14.tar.gz
Processing ./displaycal-3.9.14.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting build (from DisplayCAL==3.9.14)
  Using cached build-1.2.2.post1-py3-none-any.whl.metadata (6.5 kB)
-->8--
Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
Building wheels for collected packages: DisplayCAL
  Building wheel for DisplayCAL (pyproject.toml) ... done
  Created wheel for DisplayCAL: filename=DisplayCAL-3.9.14-cp312-cp312-linux_x86_64.whl size=10001286 sha256=095ce1b003653b5f2e220f56666b3ed8f0250c1b81a56cabe3dd7b76b8b943b0
  Stored in directory: /home/crystal/.cache/pip/wheels/ef/ac/cf/25f9672a14f9f6126bf342ef9a20a505c46be1f887b483aa49
Successfully built DisplayCAL
Installing collected packages: ifaddr, zeroconf, urllib3, six, Send2Trash, pyproject_hooks, protobuf, Pillow, packaging, numpy, idna, distro, dbus-python, charset-normalizer, certifi, wxPython, requests, build, casttube, PyChromecast, DisplayCAL
Successfully installed DisplayCAL-3.9.14 Pillow-11.0.0 PyChromecast-14.0.5 Send2Trash-1.8.3 build-1.2.2.post1 casttube-0.2.1 certifi-2024.8.30 charset-normalizer-3.4.0 dbus-python-1.3.2 distro-1.9.0 idna-3.10 ifaddr-0.2.0 numpy-2.1.3 packaging-24.1 protobuf-5.28.3 pyproject_hooks-1.2.0 requests-2.32.3 six-1.16.0 urllib3-2.2.3 wxPython-4.2.2 zeroconf-0.136.0
(env) ┌ ~/D/python_venv
╰
```

But I also noticed that the pip wheels don't seem to work?

```fish
┌ ~
╰ pipx install DisplayCal==3.9.14
Fatal error from pip prevented installation. Full pip output in file:
    /home/crystal/.local/state/pipx/log/cmd_2024-11-02_21.26.09_pip_errors.log

pip failed to build package:
    displaycal

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    error: can't copy '/tmp/pip-install-3e5vryyd/displaycal_d3182d306c214e0b858c413c77931eac/DisplayCAL/../dist/copyright': doesn't exist or not a regular file
    ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (displaycal)

Error installing displaycal from spec 'displaycal==3.9.14'.
```

Any ideas here?

**Comment by eoyilmaz** [comment]
> Any ideas here?

We didn't release DisplayCAL 3.9.15 yet, so the changes has not been published to PyPI yet, so it is normal that it is not working.
