### ISSUE TITLE
beep.wav and others not properly transferred with package_data

### ISSUE THREAD

**Issue by pablovesnine** [eoyilmaz/displaycal-py3#348]
I am encountering problems launching DisplayCAL. Building it was successful without any issues. However, after executing "make launch," the following errors occurred:

```
Warning: No language files found. The following places have been searched:
/home/vesnine/displaycal-py3/.venv/share/DisplayCAL/lang
/home/vesnine/displaycal-py3/.venv/lib/python3.11/site-packages/DisplayCAL/lang
/home/vesnine/displaycal-py3/.venv/lib/python3.11/site-packages/share/lang
/home/vesnine/displaycal-py3/.venv/lib/python3.11/site-packages/share/DisplayCAL/lang
/home/vesnine/.local/share/DisplayCAL/lang
/usr/share/ubuntu/DisplayCAL/lang
/usr/share/gnome/DisplayCAL/lang
/usr/local/share/DisplayCAL/lang
/usr/share/DisplayCAL/lang
/var/lib/snapd/desktop/DisplayCAL/lang
/var/lib/DisplayCAL/lang
/usr/share/ubuntu/doc/DisplayCAL-3.9.12/lang
/usr/share/gnome/doc/DisplayCAL-3.9.12/lang
/usr/local/share/doc/DisplayCAL-3.9.12/lang
/usr/share/doc/DisplayCAL-3.9.12/lang
/var/lib/snapd/desktop/doc/DisplayCAL-3.9.12/lang
/var/lib/doc/DisplayCAL-3.9.12/lang
/home/vesnine/.local/share/doc/DisplayCAL-3.9.12/lang
/usr/share/ubuntu/doc/packages/DisplayCAL/lang
/usr/share/gnome/doc/packages/DisplayCAL/lang
/usr/local/share/doc/packages/DisplayCAL/lang
/usr/share/doc/packages/DisplayCAL/lang
/var/lib/snapd/desktop/doc/packages/DisplayCAL/lang
/var/lib/doc/packages/DisplayCAL/lang
/home/vesnine/.local/share/doc/packages/DisplayCAL/lang
/usr/share/ubuntu/doc/DisplayCAL/lang
/usr/share/gnome/doc/DisplayCAL/lang
/usr/local/share/doc/DisplayCAL/lang
/usr/share/doc/DisplayCAL/lang
/var/lib/snapd/desktop/doc/DisplayCAL/lang
/var/lib/doc/DisplayCAL/lang
/home/vesnine/.local/share/doc/DisplayCAL/lang
/usr/share/ubuntu/doc/displaycal/lang
/usr/share/gnome/doc/displaycal/lang
/usr/local/share/doc/displaycal/lang
/usr/share/doc/displaycal/lang
/var/lib/snapd/desktop/doc/displaycal/lang
/var/lib/doc/displaycal/lang
/home/vesnine/.local/share/doc/displaycal/lang
/usr/share/ubuntu/icons/hicolor/lang
/usr/share/gnome/icons/hicolor/lang
/usr/local/share/icons/hicolor/lang
/usr/share/icons/hicolor/lang
/var/lib/snapd/desktop/icons/hicolor/lang
/var/lib/icons/hicolor/lang
/home/vesnine/.local/share/icons/hicolor/lang
NoneType: None
```

Upon closing the first error, another error appeared:

```
resources.notfound.error
lang/en.yaml
Traceback (most recent call last):
  File "/home/vesnine/displaycal-py3/.venv/lib/python3.11/site-packages/DisplayCAL/main.py", line 550, in main
    _main(module, name, app_lock_file_name)
  File "/home/vesnine/displaycal-py3/.venv/lib/python3.11/site-packages/DisplayCAL/main.py", line 486, in _main
    raise ResourceError(
DisplayCAL.debughelpers.ResourceError: resources.notfound.error
lang/en.yaml
```

Terminal Output:

```
make launch
source ./.venv/bin/activate; \
displaycal
Acquired lock file: <DisplayCAL.main.AppLock object at 0x70a2c65f3450>
displaycal 3.9.12 2024-04-01T07:44:42Z
ubuntu 23.10 mantic x86_64
Python 3.11.8 (main, Feb 25 2024, 16:39:33) [GCC 11.4.0]
Faulthandler 
wxPython 4.2.1 gtk3 (phoenix) wxWidgets 3.2.2.1
Encoding: utf-8
File system encoding: utf-8
listening
writing to lock file: port: 15411
NoneType: None
┌──────────────────────────────────────────────────────────────────────────────┐
│ NoneType: None                                                               │
└──────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "/home/vesnine/displaycal-py3/.venv/lib/python3.11/site-packages/DisplayCAL/main.py", line 550, in main
    _main(module, name, app_lock_file_name)
  File "/home/vesnine/displaycal-py3/.venv/lib/python3.11/site-packages/DisplayCAL/main.py", line 486, in _main
    raise ResourceError(
DisplayCAL.debughelpers.ResourceError: resources.notfound.error
lang/en.yaml
┌──────────────────────────────────────────────────────────────────────────────┐
│ Traceback (most recent call last):                                           │
│   File                                                                       │
│ "/home/vesnine/displaycal-py3/.venv/lib/python3.11/site-packages/DisplayCAL/main.py", │
│ line 550, in main                                                            │
│     _main(module, name, app_lock_file_name)                                  │
│   File                                                                       │
│ "/home/vesnine/displaycal-py3/.venv/lib/python3.11/site-packages/DisplayCAL/main.py", │
│ line 486, in _main                                                           │
│     raise ResourceError(                                                     │
│ DisplayCAL.debughelpers.ResourceError: resources.notfound.error              │
│ lang/en.yaml                                                                 │
└──────────────────────────────────────────────────────────────────────────────┘
Exiting displaycal
Ran application exit handlers
```

The file "en.yaml" does exist:

```
vesnine@vesnine-ubuntu:~/displaycal-py3/DisplayCAL/lang$ ls
de.yaml  es.yaml  it.yaml  ru.yaml   zh_cn.yaml
en.yaml  fr.yaml  ko.yaml  ukr.yaml  zh_hk.yaml
```

It seems there might be an issue with the program not detecting the language files correctly. Any insights would be appreciated. Thanks!

**Comment by embermann** [comment]
same for me

**Comment by elaterite** [comment]
Same error for me as well. Linux Mint 21.3.

**Comment by lbux** [comment]
I think the build process it not properly creating the lang folder. You can manually create a lang folder in any of the directories it searches and then copy the .yaml file over. I used conda, so my workaround was this:

```
mkdir lang (make sure you are in the directory of where it is searching)
cp ~/displayCAL-py3/displayCAL/lang/en.yaml ~/miniconda3/envs/displayCAL/share/DisplayCAL/lang/
```

**Comment by lbux** [comment]
> but now it's throwing a traceback because it can't find "beep.wav"

yes, this happened to me as well. I just gave up after that because it's very likely other files will be impacted as well.

On Windows (what I have access to RN as opposed to linux), beep.wav is in the environment folder under site-packages/displayCAL. On Linux it might be expected to be in a similar directory which in your case might be `/home/vesnine/displaycal-py3/.venv/lib/python3.11/site-packages/DisplayCAL`

**Comment by lbux** [comment]
Most recent change to setup.py was two weeks ago: https://github.com/eoyilmaz/displaycal-py3/commits/842e1ac85a2288a668fa605321c3b16e2696a5a2/DisplayCAL/setup.py

Perhaps a change here messed up the build process for Linux. Will need a maintainer to double check.

**Comment by embermann** [comment]
# My error in terminal
source ./.venv/bin/activate; \
displaycal
Acquired lock file: <DisplayCAL.main.AppLock object at 0x7d2335237bb0>
displaycal 3.9.12 2024-04-02T08:27:28Z
neon 22.04 jammy x86_64
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Faulthandler 
wxPython 4.2.1 gtk3 (phoenix) wxWidgets 3.2.2.1
Encoding: utf-8
File system encoding: utf-8
listening
writing to lock file: port: 15411
/home/user/Projects/OWN/displaycal-py3/.venv/lib/python3.10/site-packages/DisplayCAL/colord.py:40: Warning: DBusObjectError('org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ColorManager was not provided by any .service files: org.freedesktop.ColorManager')
  warnings.warn(safe_str(exception), Warning)
Traceback (most recent call last):
  File "/home/user/Projects/OWN/displaycal-py3/.venv/lib/python3.10/site-packages/DisplayCAL/main.py", line 550, in main
    _main(module, name, app_lock_file_name)
  File "/home/user/Projects/OWN/displaycal-py3/.venv/lib/python3.10/site-packages/DisplayCAL/main.py", line 486, in _main
    raise ResourceError(
DisplayCAL.debughelpers.ResourceError: Fatal error: A required file has not been found:
beep.wav
──────────────────────┐
│ Traceback (most recent call last):                                           │
│   File                                                                       │
│ "/home/user/Projects/OWN/displaycal-py3/.venv/lib/python3.10/site-packages/DisplayCAL/main.py", │
│ line 550, in main                                                            │
│     _main(module, name, app_lock_file_name)                                  │
│   File                                                                       │
│ "/home/user/Projects/OWN/displaycal-py3/.venv/lib/python3.10/site-packages/DisplayCAL/main.py", │
│ line 486, in _main                                                           │
│     raise ResourceError(                                                     │
│ DisplayCAL.debughelpers.ResourceError: Fatal error: A required file has not  │
│ been found:                                                                  │
│ beep.wav                                                                     │
──────────────────────┘
Exiting displaycal
Ran application exit handlers

**Comment by rickdoesdev** [comment]
Some experimenting with the DisplayCal/setup.py mostly fixes this. Based on @lbux 's comment:

it looks like the change to the get_data method at https://github.com/eoyilmaz/displaycal-py3/commit/b91fc551cd6f1a9615ba309643bf51e8c3f925ad#diff-96b3f59dd8ec09e7886d6f2e65cdf97d464d04ca1eb44009ad0c3fa90f255a2fL385-R389 causes the build step to be unable to find any of the files it's trying to copy into place.

```
warning: no files found matching 'MANIFEST'
warning: no files found matching 'use-distutils'
warning: no files found matching '_in_process.py'
warning: no files found matching '_in_process.cfg'
warning: no files found matching 'beep.wav'
warning: no files found matching 'camera_shutter.wav'
warning: no files found matching 'ColorLookupTable.fx'
warning: no files found matching 'lang/de.yaml'
warning: no files found matching 'lang/en.yaml'
warning: no files found matching 'lang/es.yaml'
warning: no files found matching 'lang/fr.yaml'
warning: no files found matching 'lang/it.yaml'
warning: no files found matching 'lang/ko.yaml'
warning: no files found matching 'lang/ru.yaml'
warning: no files found matching 'lang/ukr.yaml'
warning: no files found matching 'lang/zh_cn.yaml'
warning: no files found matching 'lang/zh_hk.yaml'
warning: no files found matching 'linear.cal'
warning: no files found matching 'pnp.ids'
warning: no files found matching 'presets/default.icc'
warning: no files found matching 'presets/laptop.icc'
warning: no files found matching 'presets/office_web.icc'
warning: no files found matching 'presets/photo.icc'
warning: no files found matching 'presets/sRGB.icc'
warning: no files found matching 'presets/softproof.icc'
warning: no files found matching 'presets/video.icc'
warning: no files found matching 'presets/video_Prisma.icc'
warning: no files found matching 'presets/video_ReShade.icc'
warning: no files found matching 'presets/video_eeColor.icc'
warning: no files found matching 'presets/video_madVR.icc'
warning: no files found matching 'presets/video_madVR_ST2084.icc'
warning: no files found matching 'presets/video_resolve.icc'
warning: no files found matching 'presets/video_resolve_ST2084_clip.icc'
warning: no files found matching 'ref/ColorCheckerDC.cie'
warning: no files found matching 'ref/ColorCheckerSG.cie'
warning: no files found matching 'ref/ClayRGB1998.gam'
warning: no files found matching 'ref/SMPTE431_P3.gam'
warning: no files found matching 'ref/sRGB.gam'
warning: no files found matching 'ref/ACES.icm'
warning: no files found matching 'ref/ACEScg.icm'
warning: no files found matching 'ref/DCDM'
warning: no files found matching 'X'Y'Z'.icm'
warning: no files found matching 'ref/Rec2020_2084.icm'
warning: no files found matching 'ref/Rec2020_HLG1000_cLUT.icm'
warning: no files found matching 'ref/SMPTE240M.icm'
warning: no files found matching 'ref/SMPTE431_P3_D65.icm'
warning: no files found matching 'ref/SMPTE431_P3_D65_2084.icm'
warning: no files found matching 'ref/SMPTE431_P3_D65_HLG1000_cLUT.icm'
warning: no files found matching 'ref/XYZ'
warning: no files found matching 'D50'
warning: no files found matching '(ICC'
warning: no files found matching 'PCS'
warning: no files found matching 'encoding).icm'
warning: no files found matching 'ref/XYZ'
warning: no files found matching 'D50.icm'
warning: no files found matching 'ref/CMYK_IDEAlliance_ControlStrip_2009.ti1'
warning: no files found matching 'ref/CMYK_IDEAlliance_ISO_12647-7_Control_Wedge_2013.ti1'
warning: no files found matching 'ref/CMYK_ISO_12647-7_outer_gamut.ti1'
warning: no files found matching 'ref/ISO_12646-2008_color_accuracy_and_gray_balance.ti1'
warning: no files found matching 'ref/ISO_14861_color_accuracy_RGB318.ti1'
warning: no files found matching 'ref/verify.ti1'
warning: no files found matching 'ref/verify_extended.ti1'
warning: no files found matching 'ref/verify_grayscale.ti1'
warning: no files found matching 'ref/verify_large.ti1'
warning: no files found matching 'ref/verify_video.ti1'
warning: no files found matching 'ref/verify_video_extended.ti1'
warning: no files found matching 'ref/verify_video_extended_hlg_p3_2020.ti1'
warning: no files found matching 'ref/verify_video_extended_smpte2084_1000_p3_2020.ti1'
warning: no files found matching 'ref/verify_video_extended_smpte2084_100_p3_2020.ti1'
warning: no files found matching 'ref/verify_video_extended_smpte2084_200_p3_2020.ti1'
warning: no files found matching 'ref/verify_video_extended_smpte2084_500_p3_2020.ti1'
warning: no files found matching 'ref/verify_video_large.ti1'
warning: no files found matching 'ref/verify_video_xl.ti1'
warning: no files found matching 'ref/verify_video_xxl.ti1'
warning: no files found matching 'ref/verify_video_xxxl.ti1'
warning: no files found matching 'ref/verify_xl.ti1'
warning: no files found matching 'ref/verify_xxl.ti1'
warning: no files found matching 'ref/verify_xxxl.ti1'
warning: no files found matching 'report/base.css'
warning: no files found matching 'report/compare.css'
warning: no files found matching 'report/print.css'
warning: no files found matching 'report/report.html'
warning: no files found matching 'report/uniformity.html'
warning: no files found matching 'report/compare.constants.js'
warning: no files found matching 'report/compare.functions.js'
warning: no files found matching 'report/compare.init.js'
warning: no files found matching 'report/compare.variables.js'
warning: no files found matching 'report/jsapi-packages.js'
warning: no files found matching 'report/jsapi-patches.js'
warning: no files found matching 'report/uniformity.functions.js'
warning: no files found matching 'test.cal'
warning: no files found matching 'theme/checkerboard-10x10x2-333-444.png'
warning: no files found matching 'theme/checkerboard-32x32x5-333-444.png'
warning: no files found matching 'theme/colorwheel.png'
warning: no files found matching 'theme/colorwheel@2x.png'
warning: no files found matching 'theme/cross-2px-12x12-fff.png'
warning: no files found matching 'theme/dashed-16x2-666.png'
warning: no files found matching 'theme/dropdown-arrow.png'
warning: no files found matching 'theme/dropdown-arrow@2x.png'
warning: no files found matching 'theme/gradient.png'
warning: no files found matching 'theme/header.png'
warning: no files found matching 'theme/header@2x.png'
warning: no files found matching 'theme/header_minimal.png'
warning: no files found matching 'theme/header_minimal@2x.png'
warning: no files found matching 'theme/headericon.png'
warning: no files found matching 'theme/headericon@2x.png'
warning: no files found matching 'theme/marker_btm.png'
warning: no files found matching 'theme/marker_btm@2x.png'
warning: no files found matching 'theme/marker_top.png'
warning: no files found matching 'theme/marker_top@2x.png'
warning: no files found matching 'theme/sash-left.png'
warning: no files found matching 'theme/sash-right.png'
warning: no files found matching 'theme/sash.png'
warning: no files found matching 'theme/shadow-bordertop.png'
warning: no files found matching 'theme/shadow.png'
warning: no files found matching 'theme/solid-16x1-fff.png'
warning: no files found matching 'theme/solid-16x2-666.png'
warning: no files found matching 'theme/splash-mask.png'
warning: no files found matching 'theme/splash.png'
warning: no files found matching 'theme/splash_version.png'
warning: no files found matching 'theme/tab_hilite.png'
warning: no files found matching 'theme/tab_hilite@2x.png'
warning: no files found matching 'theme/tab_selected.png'
warning: no files found matching 'theme/tab_selected@2x.png'
warning: no files found matching 'theme/x-2px-12x12-999.png'
warning: no files found matching 'theme/x-2px-12x12-999@2x.png'
warning: no files found matching 'theme/beep_boop.wav'
warning: no files found matching 'theme/engine_hum_loop.wav'
warning: no files found matching 'theme/intro_new.wav'
warning: no files found matching 'theme/pulsing_loop.wav'
warning: no files found matching 'theme/jet_anim/jet_anim_01.png'
warning: no files found matching 'theme/jet_anim/jet_anim_02.png'
warning: no files found matching 'theme/jet_anim/jet_anim_03.png'
warning: no files found matching 'theme/jet_anim/jet_anim_04.png'
warning: no files found matching 'theme/jet_anim/jet_anim_05.png'
warning: no files found matching 'theme/jet_anim/jet_anim_06.png'
warning: no files found matching 'theme/jet_anim/jet_anim_07.png'
warning: no files found matching 'theme/jet_anim/jet_anim_08.png'
warning: no files found matching 'theme/patch_anim/patch_anim_01.png'
warning: no files found matching 'theme/patch_anim/patch_anim_02.png'
warning: no files found matching 'theme/patch_anim/patch_anim_03.png'
warning: no files found matching 'theme/patch_anim/patch_anim_04.png'
warning: no files found matching 'theme/patch_anim/patch_anim_05.png'
warning: no files found matching 'theme/patch_anim/patch_anim_06.png'
warning: no files found matching 'theme/patch_anim/patch_anim_07.png'
warning: no files found matching 'theme/patch_anim/patch_anim_08.png'
warning: no files found matching 'theme/patch_anim/patch_anim_09.png'
warning: no files found matching 'theme/splash_anim/splash_anim_01.png'
warning: no files found matching 'theme/splash_anim/splash_anim_02.png'
warning: no files found matching 'theme/splash_anim/splash_anim_03.png'
warning: no files found matching 'theme/splash_anim/splash_anim_04.png'
warning: no files found matching 'theme/splash_anim/splash_anim_05.png'
warning: no files found matching 'theme/splash_anim/splash_anim_06.png'
warning: no files found matching 'theme/splash_anim/splash_anim_07.png'
warning: no files found matching 'theme/splash_anim/splash_anim_08.png'
warning: no files found matching 'theme/splash_anim/splash_anim_09.png'
warning: no files found matching 'theme/splash_anim/splash_anim_10.png'
warning: no files found matching 'theme/splash_anim/splash_anim_11.png'
warning: no files found matching 'theme/splash_anim/splash_anim_12.png'
warning: no files found matching 'theme/splash_anim/splash_anim_13.png'
warning: no files found matching 'theme/splash_anim/splash_anim_14.png'
warning: no files found matching 'theme/splash_anim/splash_anim_15.png'
warning: no files found matching 'theme/splash_anim/splash_anim_16.png'
warning: no files found matching 'theme/shutter_anim/shutter_anim_01.png'
warning: no files found matching 'theme/shutter_anim/shutter_anim_02.png'
warning: no files found matching 'theme/shutter_anim/shutter_anim_03.png'
warning: no files found matching 'theme/shutter_anim/shutter_anim_04.png'
warning: no files found matching 'theme/shutter_anim/shutter_anim_05.png'
warning: no files found matching 'theme/shutter_anim/shutter_anim_06.png'
warning: no files found matching 'theme/shutter_anim/shutter_anim_07.png'
warning: no files found matching 'theme/shutter_anim/shutter_anim_08.png'
warning: no files found matching 'theme/shutter_anim/shutter_anim_09.png'
warning: no files found matching 'theme/shutter_anim/shutter_anim_10.png'
warning: no files found matching 'ti1/ccxx.ti1'
warning: no files found matching 'ti1/d3-e4-s17-g52-m17-b0-f0.ti1'
warning: no files found matching 'ti1/d3-e4-s2-g28-m0-b0-f0.ti1'
warning: no files found matching 'ti1/d3-e4-s3-g52-m3-b0-f0.ti1'
warning: no files found matching 'ti1/d3-e4-s4-g52-m4-b0-f0.ti1'
warning: no files found matching 'ti1/d3-e4-s5-g52-m5-b0-f0.ti1'
warning: no files found matching 'ti1/d3-e4-s9-g52-m9-b0-f0.ti1'
warning: no files found matching 'x3d-viewer/x3d-viewer.css'
warning: no files found matching 'x3d-viewer/x3d-viewer.html'
warning: no files found matching 'x3d-viewer/x3d-viewer.js'
warning: no files found matching 'xrc/3dlut.xrc'
warning: no files found matching 'xrc/extra.xrc'
warning: no files found matching 'xrc/gamap.xrc'
warning: no files found matching 'xrc/main.xrc'
warning: no files found matching 'xrc/mainmenu.xrc'
warning: no files found matching 'xrc/report.xrc'
warning: no files found matching 'xrc/synthicc.xrc'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.backup' found anywhere in distribution
warning: no previously-included files matching '*.bak' found anywhere in distribution
```

If I revert that back to 
```
            data.append(
                (
                    os.path.normpath(os.path.join(tgt_dir, os.path.dirname(pth))),
                    safe_glob(os.path.join(src_dir, pth)),
                )
            )
```

The app builds and runs, but I still  get the much smaller list of missing files which looks mostly like the path utils aren't understanding the spaces in filenames and breaking them into separate files. I don't know python or the project well enough to feel comfortable trying to fix this right at the moment myself (it looks like `MANIFEST.in` just doesn't support spaces in paths? maybe we could use recursive include of all .icm files?), but hopefully some of this helps with figuring out the linux build issue above. 

```
warning: no files found matching 'MANIFEST'
warning: no files found matching 'use-distutils'
warning: no files found matching '_in_process.py'
warning: no files found matching '_in_process.cfg'
warning: no files found matching 'DisplayCAL/ref/DCDM'
warning: no files found matching 'X'Y'Z'.icm'
warning: no files found matching 'DisplayCAL/ref/XYZ'
warning: no files found matching 'D50'
warning: no files found matching '(ICC'
warning: no files found matching 'PCS'
warning: no files found matching 'encoding).icm'
warning: no files found matching 'DisplayCAL/ref/XYZ'
warning: no files found matching 'D50.icm'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.backup' found anywhere in distribution
warning: no previously-included files matching '*.bak' found anywhere in distribution
```

**Comment by manu-p** [comment]
Hi, same for me. I can't install an run displaycal on a new Ubuntu 22.04 machine, as I did a few month ago on my previous Ubuntu 22.04 machine.

**Comment by flipphillips** [comment]
Related to #354 also.

To fix this, if you're on an *nix system, just copy the following 'DisplayCal' subfolders/files into a `~/.local/share/DisplayCal` folder:

```
beep.wav  camera_shutter.wav  dl/  lang/  linear.cal  ref/   test.cal  theme/  ti1/  xrc/
```
Should be similar/same on mac. Windows, you're on your own :)

**Comment by johnloopi** [comment]
To be even more specific, thanks to previous finds by @lbux and @rickdoesdev, and a lot of trial and error, I've found out this:

The problem is on the green [388](https://github.com/eoyilmaz/displaycal-py3/commit/b91fc551cd6f1a9615ba309643bf51e8c3f925ad#diff-96b3f59dd8ec09e7886d6f2e65cdf97d464d04ca1eb44009ad0c3fa90f255a2fL385-R389) line and it is this:
`safe_path = [relpath(p, src_dir) for p in safe_glob(os.path.join(src_dir, pth))]`
And even though it builds and installs perfectly fine, when launching the software, as spotted by @pablovesnine, it throws an error.

But if I make a small change to that line and remove `[relpath(p, src_dir) for p in  ` and also remove the `]` at the end of the line, then I'm left with this: `safe_path = safe_glob(os.path.join(src_dir, pth))`

And I can keep all the other changes of that specific commit in place and it will build, install, and launch without any issues.

Sure, it stills spits out

> warning: no files found matching 'MANIFEST'
> warning: no files found matching 'use-distutils'
> warning: no files found matching '_in_process.py'
> warning: no files found matching '_in_process.cfg'
> warning: no files found matching 'DisplayCAL/ref/DCDM'
> warning: no files found matching 'X'Y'Z'.icm'
> warning: no files found matching 'DisplayCAL/ref/XYZ'
> warning: no files found matching 'D50'
> warning: no files found matching '(ICC'
> warning: no files found matching 'PCS'
> warning: no files found matching 'encoding).icm'
> warning: no files found matching 'DisplayCAL/ref/XYZ'
> warning: no files found matching 'D50.icm'
> warning: no previously-included files matching '*~' found anywhere in distribution
> warning: no previously-included files matching '*.backup' found anywhere in distribution
> warning: no previously-included files matching '*.bak' found anywhere in distribution

but so does the main branch, so I'm not sure if it even is an error, and if it is, I don't know where to start looking in order to fix it.

I am not a programmer by far, so while I could find a possible problem, I have no idea how to even begin fixing it, so I'm hoping @eoyilmaz or some other user know will know what to do.

**Comment by eoyilmaz** [comment]
That's probably my fault, I must have introduced this while fixing #318

I'll look into this soon.

**Comment by johnloopi** [comment]
> That's probably my fault, I must have introduced this while fixing #318
> 
> I'll look into this soon.

I've seen all the commits you've pushed in the branch "367-compiled-sucessfully-in-w10-py311-but-createprocess-fails-call-to-dispread-to-measure" in the last 13 hours, so there's no stress in fixing this. Take breaks when needed. :)

**Comment by ignace72** [comment]
Hello everyone.
I still have the same problem of missing files with version 3.9.13.
Fortunately, more and more GNU/Linux distributions offer DisplayCAL packaged.

**Comment by eoyilmaz** [comment]
@ignace72 I'm on this issue now 👍

**Comment by ignace72** [comment]
Thank you.

**Comment by eoyilmaz** [comment]
anyone want to check the `348-beepwav-and-others-not-properly-transferred-with-package_data` branch?

**Comment by eoyilmaz** [comment]
Okay so, this should now be fixed with 250ea68. I tested it in a virtual Ubuntu 24.10 and DisplayCAL is at least starting as it should be. I can't run a full profiling though... So, I'll be appreciated if somebody can test it on a real Ubuntu/Debian installation and not in a virtual machine like me...

**Comment by ignace72** [comment]
No change to the missing files, whether on a hard-coded Manjaro Linux or on XUbuntu in a virtual machine.

**Comment by eoyilmaz** [comment]
@ignace72 did you try the correct branch?

```shell
git checkout 348-beepwav-and-others-not-properly-transferred-with-package_data
make clean-all venv build install launch
```

**Comment by ignace72** [comment]
I used: I used: git clone https://github.com/eoyilmaz/displaycal-py3
Your first command gives me :
fatal: neither this nor any of its parent directories (up to mount point /) is a git repository
Stop at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM is not defined).

**Comment by eoyilmaz** [comment]
You are in the wrong directory:

```shell
git clone https://github.com/eoyilmaz/displaycal-py3
cd displaycal-py3
git checkout 348-beepwav-and-others-not-properly-transferred-with-package_data
make clean-all venv build install launch
```

Btw, building the `wxPython 4.2.2` might take around 15-20 minutes, don't be alarmed that's normal.

**Comment by ignace72** [comment]
Your command lines work in my virtual machine.
In my hardened Manjaro Linux, I get the following error:
```
--- launch: Launching DisplayCAL ---
source ./.venv/bin/activate; \
displaycal
Acquired lock file: <DisplayCAL.main.AppLock object at 0x7c3cc880a240>
displaycal 3.9.13 2024-10-12T00:09:37Z
manjaro 24.1.1 Xahea x86_64
Python 3.12.6 (main, Sep 8 2024, 13:18:56) [GCC 14.2.1 20240805]
Faulthandler 
Traceback (most recent call last):
File “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/DisplayCAL/main.py”, line 550, in main
_main(module, name, app_lock_file_name)
File “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/DisplayCAL/main.py”, line 141, in _main
from DisplayCAL.wxaddons import wx
File “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/DisplayCAL/wxaddons.py”, line 9, in <module>
from DisplayCAL.wxfixes import wx, GenButton, PlateButton, get_dialogs
File “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/DisplayCAL/wxfixes.py”, line 27, in <module>
import wx
File “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/wx/__init__.py”, line 17, in <module>
from wx.core import *
File “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/wx/core.py”, line 12, in <module>
from ._core import *
ImportError: libgspell-1.so.2: cannot open shared object file: No such file or directory
┌──────────────────────────────────────────────────────────────────────────────┐
│ Traceback (most recent call last): │
│ File │
│ “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/DisplayCAL/main.py”, │
│ line 550, in main │
│ _main(module, name, app_lock_file_name) │
│ File │
│ “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/DisplayCAL/main.py”, │
│ line 141, in _main │
│ from DisplayCAL.wxaddons import wx │
│ File │
│ “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/DisplayCAL/wxaddons.py”, │
│ line 9, in <module> │
│ from DisplayCAL.wxfixes import wx, GenButton, PlateButton, get_dialogs │
│ File │
│ “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/DisplayCAL/wxfixes.py”, │
│ line 27, in <module> │
│ import wx │
│ File │
│ “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/wx/__init__.py”, │
│ line 17, in <module> │
│ from wx.core import * │
│ File │
│ “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/wx/core.py”, │
│ line 12, in <module> │
│ from ._core import * │
│ ImportError: libgspell-1.so.2: cannot open shared object file: No such file │
│ or directory │
└──────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
File “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/DisplayCAL/main.py”, line 550, in main
_main(module, name, app_lock_file_name)
File “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/DisplayCAL/main.py”, line 141, in _main
from DisplayCAL.wxaddons import wx
File “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/DisplayCAL/wxaddons.py”, line 9, in <module>
from DisplayCAL.wxfixes import wx, GenButton, PlateButton, get_dialogs
File “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/DisplayCAL/wxfixes.py”, line 27, in <module>
import wx
File “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/wx/__init__.py”, line 17, in <module>
from wx.core import *
File “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/wx/core.py”, line 12, in <module>
from ._core import *
ImportError: libgspell-1.so.2: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/DisplayCAL/debughelpers.py”, line 77, in handle_error
from DisplayCAL.wxaddons import wx
File “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/DisplayCAL/wxaddons.py”, line 9, in <module>
from DisplayCAL.wxfixes import wx, GenButton, PlateButton, get_dialogs
File “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/DisplayCAL/wxfixes.py”, line 27, in <module>
import wx
File “/home/ignace/displaycal-py3/displaycal-py3/.venv/lib/python3.12/site-packages/wx/__init__.py”, line 12, in <module>
__version__ = wx.__version__.VERSION_STRING
^^^^^^^^^^^^^^
AttributeError: partially initialized module 'wx' has no attribute '__version__' (most likely due to a circular import)
Warning: handle_error(): partially initialized module 'wx' has no attribute '__version__' (most likely due to a circular import)
Exiting displaycal
```

**Comment by eoyilmaz** [comment]
I'm not familiar with Manjaro, and you might need to install some packages as we explained in the [Prerequisites (Linux and MacOS)](https://github.com/eoyilmaz/displaycal-py3/?tab=readme-ov-file#prerequisites-linux-and-macos) section of the readme.

**Comment by eoyilmaz** [comment]
@ignace72  so, from what I see you might need to create a symlink to `libgspell-2.so.2`:

```shell
cd /usr/lib/
sudo ln -s libgspell-2.so libgspell-1.so
sudo ln -s libgspell-1.so libgspell-1.so.2
```

**Comment by ignace72** [comment]
Hello everyone.
Thank you, DisplayCAL is working again.
However, my bash script to launch it at will no longer works.
Do you see what's wrong?
```
#!/bin/bash
cd /home/USER/
python -m venv ./displaycal_venv
source ./displaycal_venv/bin/activate
cd ./displaycal-py3/
displaycal
```

**Comment by MStraeten** [comment]
macos app package is created, but there seems to be issues within the package, so running DisplayCAL.app fails.
 
here the packaging protocol: 
[py2app.txt](https://github.com/user-attachments/files/17350244/py2app.txt)

and here the log from failing start
[displaycal_from_app.txt](https://github.com/user-attachments/files/17350265/displaycal_from_app.txt)

`make launch` is fine

**Comment by eoyilmaz** [comment]
> Hello everyone. Thank you, DisplayCAL is working again. However, my bash script to launch it at will no longer works. Do you see what's wrong?
> 
> ```
> #!/bin/bash
> cd /home/USER/
> python -m venv ./displaycal_venv
> source ./displaycal_venv/bin/activate
> cd ./displaycal-py3/
> displaycal
> ```

yeah this doesn't seem right, what I would do is have two different scripts, first one installs it and the second one launches it.

First install it:

```shell
#!/bin/bash
cd /home/USER
git clone https://github.com/eoyilmaz/displaycal-py3.git
cd displaycal-py3
git checkout 348-beepwav-and-others-not-properly-transferred-with-package_data
make venv build install
```

and then to run it:

```shell
#!/bin/bash
cd /home/USER/displaycal
make launch
```

didn't test it obviously, but should be okay.

**Comment by eoyilmaz** [comment]
> macos app package is created, but there seems to be issues within the package, so running DisplayCAL.app fails.
> 
> here the packaging protocol: [py2app.txt](https://github.com/user-attachments/files/17350244/py2app.txt)
> 
> and here the log from failing start [displaycal_from_app.txt](https://github.com/user-attachments/files/17350265/displaycal_from_app.txt)
> 
> `make launch` is fine

There is an issue with the zlib in your case. When I generate the app it works without any issues.

**Comment by ignace72** [comment]
> > Hello everyone. Thank you, DisplayCAL is working again. However, my bash script to launch it at will no longer works. Do you see what's wrong?
> > ```
> > #!/bin/bash
> > cd /home/USER/
> > python -m venv ./displaycal_venv
> > source ./displaycal_venv/bin/activate
> > cd ./displaycal-py3/
> > displaycal
> > ```
> 
> yeah this doesn't seem right, what I would do is have two different scripts, first one installs it and the second one launches it.
> 
> First install it:
> 
> ```shell
> #!/bin/bash
> cd /home/USER
> git clone https://github.com/eoyilmaz/displaycal-py3.git
> cd displaycal-py3
> git checkout 348-beepwav-and-others-not-properly-transferred-with-package_data
> make venv build install
> ```
> 
> and then to run it:
> 
> ```shell
> #!/bin/bash
> cd /home/USER/displaycal
> make launch
> ```
> 
> didn't test it obviously, but should be okay.

Thank you very much.
For the launch script, cd /home/USER/displaycal-py3 is good.

**Comment by eoyilmaz** [comment]
ah okay thank you for the correction.

**Comment by eoyilmaz** [comment]
Apparently I merged the branch related to this issue to the `develop` branch already. And it seems that we solved this issue. Closing.

**Comment by Wedge009** [comment]
I managed to (re-)build on Ubuntu just now, I think the first time since switching to 24.04. Albeit only on the 'develop' branch, trunk is still broken. A question on that: when do you promote to trunk? Generally, I'm not really a fan of GitFlow-style branching.

The application seems to run okay but I haven't done any calibration runs yet.

**Comment by eoyilmaz** [comment]
> A question on that: when do you promote to trunk?

I understand by "trunk" you mean the "main" branch, right? So, if enough issues has been fixed/resolved since the last release, and our tests are running okay, which admitedly are not covering the whole code base nor the deployment of the application under different conditions or OSes, I try to merge the changes to main branch and do a release.

The time between releases highly depend on my availability, so it is not done on a regular basis and sometimes the releases are painfully apart from each other. But, the develop branch is generally there, most of the time containing fixes for huge issues, so people can build DisplayCAL from source and use.

By the way, coincidentally, after your comment, I did a new release, so the main branch and the PyPI version should be good for Ubuntu now.
