### ISSUE TITLE
Error opening curves (Tools:show curves): AttributeError: module 'numpy' has no attribute 'sometrue'

### ISSUE THREAD

**Issue by worldpoop** [eoyilmaz/displaycal-py3#381]
**Describe the bug**
Two errors (gui pop-up dialog boxes) when selecting Tools:show curves.  First Error:

> can only concatenate str (not "NoneType) to str

Followed by Second Error -- unending pop-up repetition until closing curves

module 'numpy' has no attribute 'sometrue'

> Traceback (most recent call last):
> File "/Users/mau/displaycal-py3/.venv/lib/python3.10/site-packages/DisplayCAL/wxLUTViewer.py", line 2193, in OnMotion
> self.UpdatePointLabel(self.client._getXY(event))
> File "/Users/mau/displaycal-py3/.venv/lib/python3.10/site-packages/DisplayCAL/wxLUTViewer.py", line 2464, in UpdatePointLabel
> self.client.UpdatePointLabel(mDataDict)
> File "/Users/mau/displaycal-py3/.venv/lib/python3.10/site-packages/DisplayCAL/wxenhancedplot.py", line 1915, in UpdatePointLabel
> if _Numeric.sometrue(
> File "/Users/mau/displaycal-py3/.venv/lib/python3.10/site-packages/numpy/__init__.py", line 410, in __getattr__
> raise AttributeError("module {!r} has no attribute "
> [DisplayCal3_curves_window_error_OUTPUT.txt](https://github.com/user-attachments/files/15984446/DisplayCal3_curves_window_error_OUTPUT.txt)

**To Reproduce**
When running DisplayCal3, select Tools:show curves

**Expected behavior**
Curves window to open without error "okay boxes" popping up continuously that prevent interaction with the curves window, until the curves window can be closed.  

**Screenshots**
Attached

**Versions (please complete the following information):**
 - MacOS Sonoma 14.5 x86_64
 - iMacPro (2017)
 - (pip 24.1) Python 3.10.5 (v3.10.5:f377153967, Jun  6 2022, 12:36:10) [Clang 13.0.0 (clang-1300.0.29.30)]
 - ArgyllCMS 3.2.0 (was 2.3.1b)
 - DisplayCAL 3.9.12 2024-06-23T03:41:13Z
![DisplayCal3_curves_window_error_1](https://github.com/eoyilmaz/displaycal-py3/assets/14328272/0efddfd2-dd0d-4dc9-aa18-0ba708153077)
![DisplayCal3_curves_window_error_2](https://github.com/eoyilmaz/displaycal-py3/assets/14328272/8e6b8cf5-a9a7-4fe1-97ce-31727e48ff06)

**Comment by papoteur-mga** [comment]
@worldpoop 
What is the version of Numpy?

**Comment by Wedge009** [comment]
I calibrated a new monitor today and encountered this as well. This seems to be a result of an update to numpy 2.0:

> sometrue |Use any instead.

https://numpy.org/doc/2.0/numpy_2_0_migration_guide.html

(Also, `sometrue` was [deprecated in numpy 1.25](https://numpy.org/doc/2.0/release/1.25.0-notes.html))

I'm not an expert on how to deal with this sort of thing, but maybe a work-around for the time being is to just cap numpy version to less than 2.0 in `requirements.txt`?

**Comment by Wedge009** [comment]
Actually, the only match for `sometrue` I could find is

https://github.com/eoyilmaz/displaycal-py3/blob/2c67f1cb8e88a827b46f7e14cba6b936b969b6c8/DisplayCAL/wxenhancedplot.py#L1915

and a couple of instances in the wxpython package. Maybe it's enough just to change `sometrue` to `any` in this case?

**Comment by papoteur-mga** [comment]
> Actually, the only match for `sometrue` I could find is
> 
> https://github.com/eoyilmaz/displaycal-py3/blob/2c67f1cb8e88a827b46f7e14cba6b936b969b6c8/DisplayCAL/wxenhancedplot.py#L1915
> 
> and a couple of instances in the wxpython package. Maybe it's enough just to change `sometrue` to `any` in this case?

And what happens if you change `sometrue` by `any`?

**Comment by eoyilmaz** [comment]
This should now be fixed with 3ee7cca164ed58a724edf46feec39d2a5ee66d52 and will be released with DisplayCAL 3.9.14

**Comment by Wedge009** [comment]
Tested at 8903be9a173f58bb39f1c70aecd36f5a31a4fc97 - the specific issue of `numpy.sometrue` seems to be resolved with merging of #408 but it looks like there are lingering references to `wxenhancedplot._Numeric` in `wxLUTViewer`:
https://github.com/eoyilmaz/displaycal-py3/blob/3e216cb334209e9e771e5a0f4f23783289511ff0/DisplayCAL/wxLUTViewer.py#L535-L541

I tested the changes in #430 and this seems to resolve the lingering problem.

**Comment by d1ffuser** [comment]
I'm still encountering this issue in version 3.9.14.

Am I missing something?

I very much appreciate the work everyone is putting in to keep this project alive.

**Comment by eoyilmaz** [comment]
#430 , which was solving the remaining issues related to `numpy`, is merged but not released yet. It will be available in DisplayCAL 3.9.15, which we should have released by now but still waiting to solve some Windows related issues.
