### ISSUE TITLE
Probem to build 3.9.13 and errors on startup 

### ISSUE THREAD

**Issue by marillat** [eoyilmaz/displaycal-py3#404]
The build fail with this error for all files listed in `package_data` from DisplayCAL/setup.py
```
*** /home/marillat/displaycal-py3-3.9.13/setup.py install --root /home/marillat/displaycal-py3-3.9.13/debian/displaycal
using distutils
error: can't copy 'beep.wav': doesn't exist or not a regular file
E: pybuild pybuild:389: install: plugin distutils failed with: exit code=1: /usr/bin/python3 setup.py install --root /home/marillat/displaycal-py3-3.9.13/debian/displaycal
```
I "solved" this issue by prepending `DisplayCAL/` to all files but these files are not installed in debian/tmp
 at all and `displaycal` fail to start with these two errors:
```
writing to lock file: port: 15411
NoneType: None
┌──────────────────────────────────────────────────────────────────────────────┐
│ NoneType: None                                                               │
└──────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/DisplayCAL/main.py", line 550, in main
    _main(module, name, app_lock_file_name)
  File "/usr/lib/python3/dist-packages/DisplayCAL/main.py", line 486, in _main
    raise ResourceError(
DisplayCAL.debughelpers.ResourceError: resources.notfound.error
lang/en.yaml
┌──────────────────────────────────────────────────────────────────────────────┐
│ Traceback (most recent call last):                                           │
│   File "/usr/lib/python3/dist-packages/DisplayCAL/main.py", line 550, in     │
│ main                                                                         │
│     _main(module, name, app_lock_file_name)                                  │
│   File "/usr/lib/python3/dist-packages/DisplayCAL/main.py", line 486, in     │
│ _main                                                                        │
│     raise ResourceError(                                                     │
│ DisplayCAL.debughelpers.ResourceError: resources.notfound.error              │
│ lang/en.yaml                                                                 │
└──────────────────────────────────────────────────────────────────────────────┘
Exiting displaycal
```

**Comment by marillat** [comment]
You can read the last build log for amd64
https://buildd.debian.org/status/fetch.php?pkg=displaycal-py3&arch=amd64&ver=3.9.13-1&stamp=1728562741&raw=0

**Comment by eoyilmaz** [comment]
should be fixed with 900152f

I couldn't test it with a linux box but I will try to test and report back today.

**Comment by marillat** [comment]
This patch doesn't solve this issue.
Errors about can't find file xxx are gone but files aren't installed.

Otherwise why to not use CI to test installation in various OS ?
https://docs.github.com/en/actions/about-github-actions/about-continuous-integration-with-github-actions

**Comment by eoyilmaz** [comment]
> Otherwise why to not use CI to test installation in various OS ?

Yeah, I was thinking the same...

**Comment by eoyilmaz** [comment]
I think I solved this for Ubuntu with 250ea68

also let's handle this over #348
