### ISSUE TITLE
DisplayCAL-profile-info: concatenate str error

### ISSUE THREAD

**Issue by marjue12255** [eoyilmaz/displaycal-py3#86]
Hello

When choosing a profile for comparisson an error is raised.
`can only concatenate str (not "NoneType") to str`

```
marcus@mac-macbook:displaycal-py3 ./install_1/bin/displaycal-profile-info -d
[D] pydir: /Users/marcus/Entwicklung/github/displaycal-py3/install_1/lib/python3.9/site-packages/DisplayCAL
[D] dirname(os.path.abspath(sys.argv[0])): /Users/marcus/Entwicklung/github/displaycal-py3/install_1/bin
[D] pydir parent: /Users/marcus/Entwicklung/github/displaycal-py3/install_1/lib/python3.9/site-packages
[D] Data files search paths:
[D] /Users/marcus/Entwicklung/github/displaycal-py3/install_1/share/DisplayCAL
[D] /Users/marcus/Entwicklung/github/displaycal-py3/install_1/lib/python3.9/site-packages/DisplayCAL
[D] /Users/marcus/Entwicklung/github/displaycal-py3/install_1/lib/python3.9/site-packages/share/DisplayCAL
[D] /Users/marcus/Library/Application Support/DisplayCAL
[D] /Library/Application Support/DisplayCAL
Acquired lock file: <DisplayCAL.main.AppLock object at 0x104ed4af0>
displaycal-profile-info 3.9.0 2022-04-07T12:37:31Z
Mac OS X 12.3.1 arm64
Python 3.9.10 (v3.9.10:f2f3f53782, Jan 13 2022, 16:55:45)
[Clang 13.0.0 (clang-1300.0.29.30)]
CA file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/certifi/cacert.pem
Faulthandler
wxPython 4.1.1 osx-cocoa (phoenix) wxWidgets 3.1.5
Encoding: utf-8
File system encoding: utf-8
Loading /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL.ini
Loading /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL-profile-info.ini
listening
writing to lock file: port: 15411
Starte Skript-Host unter 127.0.0.1:15411
[D] check_argyll_bin OK
[D] wrapup(copy=False, remove=True)
[D] check_argyll_bin OK
In:
1.0000 0.0000 0.0000
1.0000 0.0256 0.0000
1.0000 0.0513 0.0000
...
0.0000 0.9487 1.0000
0.0000 0.9744 1.0000
0.0000 1.0000 1.0000
1.0000 1.0000 1.0000
[D] wrapup(copy=False, remove=True)
┌──────────────────────────────────────────────────────────────────────────────┐
│ can only concatenate str (not "NoneType") to str                             │
└──────────────────────────────────────────────────────────────────────────────┘
[D] wrapup(copy=False, remove=True)
Executing BaseApp.OnExit()
Running application exit handlers
Waiting for thread ScriptingHost.ConnectionHandler to exit
ScriptingHost.ConnectionHandler exited
Exiting displaycal-profile-info
Ran application exit handlers
```

Greetings
Marcus

**Comment by eoyilmaz** [comment]
Hi, can you step by step explain the required actions to reproduce the error. Because there is no line number or python file name in the error message I can't pinpoint the error.

**Comment by marjue12255** [comment]
Hello
That's simple.

1. Start the programm
2. Klick in 'Comparison Profile' to change the value'
3. Choose one of the profiles.

The error pops up immediately in that moment I click on the wanted profile name from the list. It does not matter which one is chosen.

Greetings
Marcus

**Comment by eoyilmaz** [comment]
Hey Marucs,

I can not produce the error. But I wrapped the ``comparison_profile_select_handler`` (which is the event handler) with a ``try...except`` block, if it is raising the error, we should see the source of it now.

Can you try again, please :+1:

**Comment by marjue12255** [comment]
Hi

I don't see much difference

```
[D] pydir: /Users/marcus/Entwicklung/github/displaycal-py3/install_1/lib/python3.9/site-packages/DisplayCAL
[D] dirname(os.path.abspath(sys.argv[0])): /Users/marcus/Entwicklung/github/displaycal-py3/install_1/bin
[D] pydir parent: /Users/marcus/Entwicklung/github/displaycal-py3/install_1/lib/python3.9/site-packages
[D] Data files search paths:
[D] /Users/marcus/Entwicklung/github/displaycal-py3/install_1/share/DisplayCAL
[D] /Users/marcus/Entwicklung/github/displaycal-py3/install_1/lib/python3.9/site-packages/DisplayCAL
[D] /Users/marcus/Entwicklung/github/displaycal-py3/install_1/lib/python3.9/site-packages/share/DisplayCAL
[D] /Users/marcus/Library/Application Support/DisplayCAL
[D] /Library/Application Support/DisplayCAL
Acquired lock file: <DisplayCAL.main.AppLock object at 0x10072caf0>
displaycal-profile-info 3.9.0 2022-04-10T12:05:53Z
Mac OS X 12.3.1 arm64
Python 3.9.10 (v3.9.10:f2f3f53782, Jan 13 2022, 16:55:45)
[Clang 13.0.0 (clang-1300.0.29.30)]
CA file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/certifi/cacert.pem
Faulthandler
wxPython 4.1.1 osx-cocoa (phoenix) wxWidgets 3.1.5
Encoding: utf-8
File system encoding: utf-8
Loading /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL.ini
Loading /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL-profile-info.ini
listening
writing to lock file: port: 15411
Starte Skript-Host unter 127.0.0.1:15411
[D] check_argyll_bin OK
[D] wrapup(copy=False, remove=True)
[D] check_argyll_bin OK
In:
1.0000 0.0000 0.0000
1.0000 0.0256 0.0000
....
1.0000 1.0000 1.0000
[D] wrapup(copy=False, remove=True)
┌──────────────────────────────────────────────────────────────────────────────┐
│ can only concatenate str (not "NoneType") to str                             │
└──────────────────────────────────────────────────────────────────────────────┘
[D] wrapup(copy=False, remove=True)
Executing BaseApp.OnExit()
Running application exit handlers
Waiting for thread ScriptingHost.ConnectionHandler to exit
ScriptingHost.ConnectionHandler exited
Exiting displaycal-profile-info
Ran application exit handlers
```

**Comment by eoyilmaz** [comment]
Hey Marcus, I've updated the code again, can you please try it again, this time I'm expecting to see the source of the error.

**Comment by marjue12255** [comment]
Sorry ... again no debug info 

```
./install_1/bin/displaycal-profile-info -d
[D] pydir: /Users/marcus/Entwicklung/github/displaycal-py3/install_1/lib/python3.9/site-packages/DisplayCAL
[D] dirname(os.path.abspath(sys.argv[0])): /Users/marcus/Entwicklung/github/displaycal-py3/install_1/bin
[D] pydir parent: /Users/marcus/Entwicklung/github/displaycal-py3/install_1/lib/python3.9/site-packages
[D] Data files search paths:
[D] /Users/marcus/Entwicklung/github/displaycal-py3/install_1/share/DisplayCAL
[D] /Users/marcus/Entwicklung/github/displaycal-py3/install_1/lib/python3.9/site-packages/DisplayCAL
[D] /Users/marcus/Entwicklung/github/displaycal-py3/install_1/lib/python3.9/site-packages/share/DisplayCAL
[D] /Users/marcus/Library/Application Support/DisplayCAL
[D] /Library/Application Support/DisplayCAL
Acquired lock file: <DisplayCAL.main.AppLock object at 0x102928af0>
displaycal-profile-info 3.9.0 2022-04-11T20:36:30Z
Mac OS X 12.3.1 arm64
Python 3.9.10 (v3.9.10:f2f3f53782, Jan 13 2022, 16:55:45)
[Clang 13.0.0 (clang-1300.0.29.30)]
CA file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/certifi/cacert.pem
Faulthandler
wxPython 4.1.1 osx-cocoa (phoenix) wxWidgets 3.1.5
Encoding: utf-8
File system encoding: utf-8
Loading /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL.ini
Loading /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL-profile-info.ini
listening
writing to lock file: port: 15411
Starte Skript-Host unter 127.0.0.1:15411
[D] check_argyll_bin OK
[D] wrapup(copy=False, remove=True)
[D] check_argyll_bin OK
In:
1.0000 0.0000 0.0000
1.0000 0.0256 0.0000
...
0.0000 1.0000 1.0000
1.0000 1.0000 1.0000
[D] wrapup(copy=False, remove=True)
┌──────────────────────────────────────────────────────────────────────────────┐
│ can only concatenate str (not "NoneType") to str                             │
└──────────────────────────────────────────────────────────────────────────────┘
[D] wrapup(copy=False, remove=True)
Executing BaseApp.OnExit()
Running application exit handlers
Waiting for thread ScriptingHost.ConnectionHandler to exit
ScriptingHost.ConnectionHandler exited
Exiting displaycal-profile-info
Ran application exit handlers
```

**Comment by eoyilmaz** [comment]
Hey @marjue12255 can you test the latest code (we now have a main branch by the way).

**Comment by eoyilmaz** [comment]
@marjue12255 I've pushed a new commit to the ``develop`` branch, can you try running it and paste the output here if you still have the problem?

**Comment by marjue12255** [comment]
Hello Erkan
Sorry bad news ... I've polled the development branch now but the problem persists.

```
marcus@mac-macbook:displaycal-py3 ./install_1/bin/displaycal-profile-info -d
[D] pydir: /Users/marcus/Entwicklung/github/displaycal-py3/install_1/lib/python3.9/site-packages/DisplayCAL
[D] dirname(os.path.abspath(sys.argv[0])): /Users/marcus/Entwicklung/github/displaycal-py3/install_1/bin
[D] pydir parent: /Users/marcus/Entwicklung/github/displaycal-py3/install_1/lib/python3.9/site-packages
[D] Data files search paths:
[D] /Users/marcus/Entwicklung/github/displaycal-py3/install_1/share/DisplayCAL
[D] /Users/marcus/Entwicklung/github/displaycal-py3/install_1/lib/python3.9/site-packages/DisplayCAL
[D] /Users/marcus/Entwicklung/github/displaycal-py3/install_1/lib/python3.9/site-packages/share/DisplayCAL
[D] /Users/marcus/Library/Application Support/DisplayCAL
[D] /Library/Application Support/DisplayCAL
Acquired lock file: <DisplayCAL.main.AppLock object at 0x102400af0>
displaycal-profile-info 3.9.2 2022-05-01T18:43:30Z
Mac OS X 12.3.1 arm64
Python 3.9.10 (v3.9.10:f2f3f53782, Jan 13 2022, 16:55:45)
[Clang 13.0.0 (clang-1300.0.29.30)]
CA file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/certifi/cacert.pem
Faulthandler
wxPython 4.1.1 osx-cocoa (phoenix) wxWidgets 3.1.5
Encoding: utf-8
File system encoding: utf-8
Loading /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL.ini
Loading /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL-profile-info.ini
listening
writing to lock file: port: 15411
Starte Skript-Host unter 127.0.0.1:15411
[D] Found display 0, 0, 1728x1117 at index 0
[D] check_argyll_bin OK
[D] wrapup(copy=False, remove=True)
[D] check_argyll_bin OK
In:
1.0000 0.0000 0.0000
1.0000 0.0256 0.0000
1.0000 0.0513 0.0000
...
0.0000 0.9487 1.0000
0.0000 0.9744 1.0000
0.0000 1.0000 1.0000
1.0000 1.0000 1.0000
[D] wrapup(copy=False, remove=True)
┌──────────────────────────────────────────────────────────────────────────────┐
│ can only concatenate str (not "NoneType") to str                             │
└──────────────────────────────────────────────────────────────────────────────┘
/Users/marcus/Entwicklung/github/displaycal-py3/install_1/lib/python3.9/site-packages/DisplayCAL/colormath.py:1283: Warning: Daylight CCT is only accurate down to about 4000 K
  warnings.warn("Daylight CCT is only accurate down to about 4000 K", Warning)
[D] wrapup(copy=False, remove=True)
Executing BaseApp.OnExit()
Running application exit handlers
Waiting for thread ScriptingHost.ConnectionHandler to exit
ScriptingHost.ConnectionHandler exited
Exiting displaycal-profile-info
Ran application exit handlers
```

**Comment by eoyilmaz** [comment]
Okay, that's heart breaking. I've pushed a new commit, and I expect to see a different error message now, can you please try again.

**Comment by marjue12255** [comment]
Hello
Sorry still the same. No extra debug-info to see. I'm a little afraid of doing something wrong.

- I've cloned the branch with "`git clone -b develop https://github.com/eoyilmaz/displaycal-py3`" in /Users/marcus/Entwicklung/github/
- Then cd into displaycal-py3/
- Then installed it with "`./setup.py install --prefix /Users/marcus/Entwicklung/github/displaycal-py3/install_1`"
- There is this setting in my session "`export PYTHONPATH=/Users/marcus/Entwicklung/github/displaycal-py3/install_1/lib/python3.9/site-packages`". When it is wrong the module is not found so it seams to be correct

I've done a litte screen capture so you can see when it is happening. Maybe this helps a little.
https://www.icloud.com/iclouddrive/016e0RRUpTFnb-Os_lNtU-DDA#Bildschirmaufnahme_2022-05-02_um_19.13

**Comment by marjue12255** [comment]
Hello Erkan
Maybe this helps. I've done a debug with heartrate
https://www.icloud.com/iclouddrive/032r6hVpgNCQmk5WDuKFdZt_A#Mein_Film

Bye
Marcus

**Comment by eoyilmaz** [comment]
This is lovely, thank you. But I'm not sure if I'm getting the origin of the error. Anyways, I've update the ``develop`` branch, let's see if it is going to work for you. One another question, did you setup ArgyllCMS and showed its placement to DisplayCAL? You probably did, but let's be sure.

**Comment by marjue12255** [comment]
Hello Erkan

This is the output from my last try with the dev branch. I think it's the same as in the prior tries.
The path to argyll is set as you can see in the ini on the bottom.

```
 marcus@mac-macbook:displaycal-py3 ./install_1/bin/displaycal-profile-info -d
[D] pydir: /Users/marcus/Entwicklung/github/displaycal_develop/displaycal-py3/install_1/lib/python3.9/site-packages/DisplayCAL
[D] dirname(os.path.abspath(sys.argv[0])): /Users/marcus/Entwicklung/github/displaycal_develop/displaycal-py3/install_1/bin
[D] pydir parent: /Users/marcus/Entwicklung/github/displaycal_develop/displaycal-py3/install_1/lib/python3.9/site-packages
[D] Data files search paths:
[D] /Users/marcus/Entwicklung/github/displaycal_develop/displaycal-py3/install_1/share/DisplayCAL
[D] /Users/marcus/Entwicklung/github/displaycal_develop/displaycal-py3/install_1/lib/python3.9/site-packages/DisplayCAL
[D] /Users/marcus/Entwicklung/github/displaycal_develop/displaycal-py3/install_1/lib/python3.9/site-packages/share/DisplayCAL
[D] /Users/marcus/Library/Application Support/DisplayCAL
[D] /Library/Application Support/DisplayCAL
Acquired lock file: <DisplayCAL.main.AppLock object at 0x10317caf0>
displaycal-profile-info 3.9.3 2022-05-14T13:48:26Z
Mac OS X 12.3.1 arm64
Python 3.9.10 (v3.9.10:f2f3f53782, Jan 13 2022, 16:55:45)
[Clang 13.0.0 (clang-1300.0.29.30)]
CA file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/certifi/cacert.pem
Faulthandler
wxPython 4.1.1 osx-cocoa (phoenix) wxWidgets 3.1.5
Encoding: utf-8
File system encoding: utf-8
Loading /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL.ini
Loading /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL-profile-info.ini
Existing client using port 15411
Existing client using port 62558
listening
writing to lock file: port: 55482
Starte Skript-Host unter 127.0.0.1:55482
[D] Found display 0, 0, 2056x1329 at index 0
[D] check_argyll_bin OK
[D] wrapup(copy=False, remove=True)
[D] check_argyll_bin OK
In:
1.0000 0.0000 0.0000
1.0000 0.0256 0.0000
1.0000 0.0513 0.0000
1.0000 0.0769 0.0000
....
0.0000 0.8205 1.0000
0.0000 0.8462 1.0000
0.0000 0.8718 1.0000
0.0000 0.8974 1.0000
0.0000 0.9231 1.0000
0.0000 0.9487 1.0000
0.0000 0.9744 1.0000
0.0000 1.0000 1.0000
1.0000 1.0000 1.0000
[D] wrapup(copy=False, remove=True)
┌──────────────────────────────────────────────────────────────────────────────┐
│ can only concatenate str (not "NoneType") to str                             │
└──────────────────────────────────────────────────────────────────────────────┘
[D] wrapup(copy=False, remove=True)
Executing BaseApp.OnExit()
Running application exit handlers
Waiting for thread ScriptingHost.ConnectionHandler to exit
ScriptingHost.ConnectionHandler exited
Connection to 127.0.0.1:62558 failed: [Errno 61] Connection refused
Connection to 127.0.0.1:15411 failed: [Errno 61] Connection refused
Exiting displaycal-profile-info
Ran application exit handlers
 marcus@mac-macbook:displaycal-py3


 marcus@mac-macbook:displaycal-py3 cat ~/Library/Preferences/DisplayCAL/DisplayCAL.ini
[Default]
3dlut.gamap.use_b2a = 0
3dlut.trc = bt1886
argyll.dir = /Users/marcus/Portable/Argyll_V2.3.0/bin
argyll.version = 2.3.0
calibration.file = /Users/marcus/Entwicklung/github/displaycal-py3/install_1/lib/python3.9/site-packages/DisplayCAL/presets/default.icc
calibration.update = 0
colorimeter_correction_matrix_file = AUTO:
display.number = 1
display_lut.link = 1
displays = Built-in Retina Display @ 0, 0, 2056x1329 [PRIMARY]:Web @ localhost:madVR:Prisma:Resolve:Untethered
last_launch = 3.9.3
lut_viewer.show = 0
measurement_mode = l
profile.name = %dns %out %Y-%m-%d %H-%M %cb %wp %cB %ck %cg %cq-%pq %pt
profile.name.expanded = Display #1 2022-05-04 22-57 2.2 F-S 1xCurve+MTX
profile.update = 0
show_donation_message = 1
testchart.file = auto


 marcus@mac-macbook:displaycal-py3 cat ~/Library/Preferences/DisplayCAL/DisplayCAL-profile-info.ini
[Default]
position.profile_info.x = 999
position.profile_info.y = 334
size.profile_info.h = 723
size.profile_info.split.w = 960
size.profile_info.w = 432
```

**Comment by eoyilmaz** [comment]
Hey @marjue12255 I pushed some new changes to the ``develop`` branch, thanks to your video, I might have found the error, but, let me not get ahead of me, can you please try the latest commit in the ``develop`` branch.

**Comment by marjue12255** [comment]
Finaly ;-)
I can choose the comparison profile without an error now. It is fixed!

Greetings
Marcus

**Comment by eoyilmaz** [comment]
Oh that's good to know :+1:
