### ISSUE TITLE
small patch display

### ISSUE THREAD

**Issue by ctouz** [eoyilmaz/displaycal-py3#90]
The patch display square is smaller than on version 3.8.9, it's usable but a bit uncomfortable
https://hidrive.ionos.com/lnk/YpCAgspH

**Comment by eoyilmaz** [comment]
You can adjust the size of the window by pressing the "+" button

**Comment by ctouz** [comment]
does not work, by pressing the "+" button, the rectangle disappears then control+C and this message :b"(-c:239387):Gtk-CRITICAL **:22:54:03.094:gtk_window_resize:assertion'width > 0'failure"

**Comment by eoyilmaz** [comment]
Oh, okay so we have a bug there then. Can you run ``displaycal -d`` and then copy&paste the output here.

**Comment by ctouz** [comment]
[D] check_argyll_bin OK
ArgyllCMS est à jour.
[D] focus_handler called for ID -31577 calibrate_and_profile_btn <class 'DisplayCAL.wxwindows.BorderGradientButton'>, event type 10008 EVT_BUTTON
[D] Setting last focused control to ID -31577 calibrate_and_profile_btn <class 'DisplayCAL.wxwindows.BorderGradientButton'>
[D] check_argyll_bin OK
[D] wrapup(copy=False, remove=True)

**Comment by eoyilmaz** [comment]
Can you copy&paste the whole output to a text file and upload it here.

**Comment by eoyilmaz** [comment]
Please try again, this should be fixed now.

**Comment by ctouz** [comment]
not fixed
in the window :
b"(-c:5318):Gtk-CRITICAL **:09:34:50.597:gtk_window_resize:assertion'width > 0'failed"

in terminal:
[D] focus_handler called for ID -31577 calibrate_and_profile_btn <class 'DisplayCAL.wxwindows.BorderGradientButton'>, event type 10008 EVT_BUTTON
[D] Setting last focused control to ID -31577 calibrate_and_profile_btn <class 'DisplayCAL.wxwindows.BorderGradientButton'>
[D] check_argyll_bin OK
[D] wrapup(copy=False, remove=True)
^CReloading /home/christian/.config/DisplayCAL/DisplayCAL.ini
[D] get_set_display
[D] display_ctrl_handler called for ID -31977 display_ctrl event type 10010 EVT_CHOICE

**Comment by ctouz** [comment]
new try :fixed

**Comment by eoyilmaz** [comment]
okay, happy to hear that, thank you :+1:
